version: '2'
services:
    gitlab-runner:
        image: gitlab/gitlab-runner:latest
        volumes:
        - ~/runner/config/:/etc/gitlab-runner
        - ~/runner/docker.sock:/var/run/docker.sock
