version: '2'
services:
  gogs-mysql-server:
        image: mysql:5.7.18
        # volumes:
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=gogs
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8 --explicit_defaults_for_timestamp

  gogs-server:
        image: gogs/gogs
#        depends_on:
#             - gogs-mysql-server
        volumes:
             - ~/temp/gogs:/data/gogs
        ports:
             - 3030:3000
             - 1022:22
